### ISSUE TITLE
Windows Binaries very out of date

### ISSUE THREAD

**Issue by pghardy** [simh/Win32-Development-Binaries#3]
The Windows Development Binaries have not been rebuilt since June 2020 - some 17 months now. So they are well behind the current sources in many ways. Please can they be updated?

Note: A prerequisite should be the updating of the windows-build components as these are even more out of date - two years now.

**Comment by markpizz** [comment]
Windows build components, by design, almost never need updating.  Almost never means not until some new component is needed or some new functionality of an existing components is needed by simulation code.  A couple of year update interval is reasonable and actually more driven by changes to available compiler technology which may not be supported by the older component libraries.

Back to the Windows Binaries....  I'm now comfortable pushing updates rather frequently as changes happen in the simh repository.  New update today in fact.
